struct CursorUniforms {
  pos: vec2f,
  lastPos: vec2f,
  vel: vec2f,
  acc: vec2f,
  leftDownPos: vec2f,
  leftUpPos: vec2f,
  leftDelta: vec2f,
  leftDeltaLast: vec2f,
  rightDownPos: vec2f,
  rightUpPos: vec2f,
  rightDelta: vec2f,
  rightDeltaLast: vec2f,
  arrowDelta: vec2f,
  scrollDelta: f32,
  leftDown: f32,
  leftDownAt: f32,
  leftUpAt: f32,
  rightDown: f32,
  rightDownAt: f32,
  rightUpAt: f32,
};