struct CursorUniforms {
  pos: vec2f,
  lastPos: vec2f,
  leftDownPos: vec2f,
  leftUpPos: vec2f,
  leftDelta: vec2f,
  rightDownPos: vec2f,
  rightUpPos: vec2f,
  rightDelta: vec2f,
  leftDown: f32,
  leftDownAt: f32,
  leftUpAt: f32,
  rightDown: f32,
  rightDownAt: f32,
  rightUpAt: f32,
  vel: f32,
  acc: f32,
};